"""empty message

Revision ID: ee43b1a50858
Revises: mrgtpl01
Create Date: 2026-08-27 16:05:28.929179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee43b1a50858'
down_revision = 'mrgtpl01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_teacher_judge_sessions_selected_file'), table_name='teacher_judge_sessions', postgresql_where='(selected_file_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_teacher_judge_sessions_selected_file'), 'teacher_judge_sessions', ['selected_file_id'], unique=True, postgresql_where='(selected_file_id IS NOT NULL)')
    # ### end Alembic commands ###
